GET http://localhost:3002/users

###

GET http://localhost:3002/users/63e1e99dae0c9c7467ac7de1

###

POST http://localhost:3002/users/register
Content-Type: application/json

{
    "firstName":"Elijah",
    "lastName": "Monjardin",
    "email":"monjardinelijah121@gmail.com",
    "password": "123qwe",
    "birthDay":"August 7, 2002"
}

###

POST http://localhost:3002/users/login
Content-Type: application/json

{
    "email":"monjardinelijah121@gmail.com",
    "password": "123qwe"
}

###

DELETE http://localhost:3002/users/63e49a145fa6ad8ead6eddd2

###

PATCH http://localhost:3002/users/63d1b4dfb88158d066f68329
Content-Type: application/json

{
    "email":"changedemail@gmail.com",
    "password":"newpass"
}

###

GET http://localhost:3002/users/63d1c5ccef704ae2f5298c94/posts

###

PATCH http://localhost:3002/users/63d1c5ccef704ae2f5298c94/newPost
Content-Type: application/json

{
    "author":"Elijah M.",
    "date":"Jan 14 9:04 AM",
    "caption":"New Post",
    "comments":[],
    "likes":"test",
    "picture":"https://img.freepik.com/free-photo/lovely-pet-portrait-isolated_23-2149192357.jpg?w=1380&t=st=1673658419~exp=1673659019~hmac=0b6eb014a7e270eba7d39d77eabbaed83a47d2f62d829203ebd53e43ac1a027f"

}

###

GET http://localhost:3002/users/63d1c5ccef704ae2f5298c94/posts/0

###

DELETE http://localhost:3002/users/63d1c5ccef704ae2f5298c94/posts/0

###

PATCH http://localhost:3002/users/63d1c5ccef704ae2f5298c94/posts/0/newComment
Content-Type: application/json

{
    "name":"Trisha M.",
    "date":"Jan 14 9:04 AM",
    "content":"Wow!!!"
}

###

GET http://localhost:3002/users/logout

###

PATCH http://localhost:3002/users/63e49ce25fa6ad8ead6edddb/63ea0028a3fdf1719a0b5f85
Content-Type: application/json

{
    "tofollow":"63ea0028a3fdf1719a0b5f85"
}